version: '3.8'

services: 
  postgres:
    container_name: postgres-aula
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auladb
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
