POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "name": "ps3",
    "price": 800
}

### 
GET http://localhost:8080/products

### 
PUT http://localhost:8080/products/1 HTTP/1.1
content-type: application/json

{
    "name": "ps4",
    "price": 1200
}

### 
DELETE http://localhost:8080/products/1 HTTP/1.1